/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 목록 조회
         * @description 모든 프로젝트 목록을 조회합니다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 프로젝트 목록이 성공적으로 반환됩니다. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectListResponse"];
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description 서버 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 프로젝트 생성
         * @description 새로운 프로젝트를 생성합니다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description 프로젝트가 성공적으로 생성되었습니다. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                /** @description 잘못된 요청 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description 서버 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 상세 조회
         * @description 프로젝트 ID로 특정 프로젝트와 파일 목록을 조회합니다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 프로젝트가 성공적으로 반환됩니다. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDetailsResponse"];
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description 프로젝트를 찾을 수 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectNotFoundError"];
                    };
                };
                /** @description 서버 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 프로젝트 삭제
         * @description 프로젝트 ID로 특정 프로젝트를 삭제합니다. 프로젝트에 속한 모든 파일도 함께 삭제됩니다.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 프로젝트가 성공적으로 삭제되었습니다. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description 프로젝트를 찾을 수 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectNotFoundError"];
                    };
                };
                /** @description 서버 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/files/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presigned URL 생성
         * @description 파일 업로드를 위한 Presigned URL을 생성합니다. 클라이언트는 이 URL을 사용하여 OCI에 직접 파일을 업로드할 수 있습니다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PresignRequest"];
                };
            };
            responses: {
                /** @description Presigned URL이 성공적으로 생성되었습니다. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresignResponse"];
                    };
                };
                /** @description 잘못된 요청 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description 파일 크기 초과 또는 스토리지 한도 초과 */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/files/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 업로드 완료 확인
         * @description OCI에 직접 업로드 완료 후 호출하여 DB에 파일 레코드를 생성합니다. 이미지 파일의 경우 variants 옵션으로 변환 처리를 요청할 수 있습니다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConfirmRequest"];
                };
            };
            responses: {
                /** @description 파일 레코드가 성공적으로 생성되었습니다. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfirmResponse"];
                    };
                };
                /** @description 잘못된 요청 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description 파일을 찾을 수 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileNotFoundError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 파일 삭제
         * @description 특정 ID를 가진 파일 및 관련된 모든 버전을 삭제합니다. (OCI 스토리지 포함)
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 파일 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description 잘못된 요청 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description 파일을 찾을 수 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileNotFoundError"];
                    };
                };
                /** @description 서버 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description 에러 메시지
             * @example 요청 처리 중 오류가 발생했습니다.
             */
            message: string;
            /**
             * @description 필드별 유효성 검사 에러
             * @example {
             *       "name": [
             *         "필수 항목입니다."
             *       ]
             *     }
             */
            errors?: {
                [key: string]: string[];
            };
        };
        UnauthorizedError: {
            /**
             * @description 에러 메시지
             * @example 인증 실패: 유효하지 않은 API 키
             */
            message: string;
        };
        ProjectNotFoundError: {
            /**
             * @description 에러 메시지
             * @example 프로젝트를 찾을 수 없습니다.
             */
            message: string;
        };
        FileNotFoundError: {
            /**
             * @description 에러 메시지
             * @example 파일을 찾을 수 없습니다.
             */
            message: string;
        };
        ServerError: {
            /**
             * @description 에러 메시지
             * @example 서버 오류가 발생했습니다.
             */
            message: string;
        };
        BadRequestError: {
            /**
             * @description 에러 메시지
             * @example 잘못된 요청 형식입니다.
             */
            message: string;
            /**
             * @description 필드별 유효성 검사 에러
             * @example {
             *       "name": [
             *         "필수 항목입니다."
             *       ]
             *     }
             */
            errors?: {
                [key: string]: string[];
            };
        };
        MessageResponse: {
            /**
             * @description 성공 메시지
             * @example 작업이 완료되었습니다.
             */
            message: string;
        };
        VariantOption: {
            /**
             * @description 이미지 크기 레이블. 프리셋(original, 300x300, 800x800, 1920x1080) 또는 커스텀 해상도(WIDTHxHEIGHT 형식)
             * @example original
             */
            sizeLabel: ("source" | "max300" | "max800" | "max1920") | string;
            /**
             * @description 이미지 포맷
             * @example webp
             * @enum {string}
             */
            format: "png" | "jpeg" | "avif" | "webp";
        };
        ImageVariantData: {
            /**
             * @description 이미지 URL
             * @example https://objectstorage.ap-seoul-1.oraclecloud.com/...
             */
            url: string;
            /**
             * @description 이미지 너비 (px)
             * @example 1920
             */
            width: number;
            /**
             * @description 이미지 높이 (px)
             * @example 1080
             */
            height: number;
            /**
             * @description 파일 크기 (bytes)
             * @example 102400
             */
            size: number;
            /**
             * @description 이미지 포맷
             * @example webp
             */
            format: string;
            /**
             * @description 크기 레이블
             * @example original
             */
            label: string;
        };
        PresignRequest: {
            /**
             * @description 업로드할 파일의 이름
             * @example image.jpg
             */
            fileName: string;
            /**
             * @description 파일의 MIME 타입
             * @example image/jpeg
             */
            contentType: string;
            /**
             * @description 파일 크기 (bytes)
             * @example 102400
             */
            fileSize: number;
        };
        PresignResponse: {
            /**
             * @description OCI에 직접 업로드할 수 있는 Presigned URL
             * @example https://objectstorage.ap-seoul-1.oraclecloud.com/p/...
             */
            presignedUrl: string;
            /**
             * @description OCI 객체 경로
             * @example clq1234abcd/file5678efgh.jpg
             */
            objectName: string;
            /**
             * @description 업로드 완료 후 객체 URL
             * @example https://objectstorage.ap-seoul-1.oraclecloud.com/n/.../o/...
             */
            objectUrl: string;
            /**
             * @description 생성된 파일 ID
             * @example file5678efgh
             */
            fileId: string;
            /**
             * @description Presigned URL 만료 시간 (ISO 8601)
             * @example 2023-01-01T00:15:00.000Z
             */
            expiresAt: string;
        };
        ConfirmRequest: {
            /**
             * @description presign 응답에서 받은 파일 ID
             * @example file5678efgh
             */
            fileId: string;
            /**
             * @description presign 응답에서 받은 객체 이름
             * @example clq1234abcd/file5678efgh.jpg
             */
            objectName: string;
            /**
             * @description 원본 파일 이름
             * @example image.jpg
             */
            fileName: string;
            /**
             * @description 파일의 MIME 타입
             * @example image/jpeg
             */
            contentType: string;
            /**
             * @description 파일 크기 (bytes)
             * @example 102400
             */
            fileSize: number;
            /** @description (이미지 전용) 생성할 이미지 버전 옵션 배열 */
            variants?: components["schemas"]["VariantOption"][];
        };
        FileResponse: {
            /**
             * @description 파일 ID
             * @example file5678efgh
             */
            id: string;
            /**
             * @description 파일 이름
             * @example image.jpg
             */
            name: string;
            /**
             * @description MIME 타입
             * @example image/jpeg
             */
            mimeType: string;
            /**
             * @description 이미지 파일 여부
             * @example true
             */
            isImage: boolean;
            /**
             * @description 파일 크기 (bytes)
             * @example 102400
             */
            size: number;
            /**
             * @description 비이미지 파일의 URL
             * @example null
             */
            url: string | null;
            /** @description 이미지 버전 목록 (이미지 파일만 해당) */
            variants: components["schemas"]["ImageVariantData"][];
            /**
             * @description 생성 일시 (ISO 8601)
             * @example 2023-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description 수정 일시 (ISO 8601)
             * @example 2023-01-01T00:00:00.000Z
             */
            updatedAt: string;
            /**
             * @description 프로젝트 ID
             * @example clq1234abcd
             */
            projectId: string;
        };
        ConfirmResponse: {
            /**
             * @description 성공 메시지
             * @example 파일 업로드 완료
             */
            message: string;
            file: components["schemas"]["FileResponse"];
            /** @description 생성된 이미지 버전 목록 */
            variants?: components["schemas"]["ImageVariantData"][];
        };
        CreateProjectRequest: {
            /**
             * @description 프로젝트 이름 (3-50자)
             * @example 내 웹사이트 에셋
             */
            name: string;
            /**
             * @description 프로젝트 설명 (최대 200자)
             * @example 웹사이트에서 사용할 이미지 모음
             */
            description?: string;
            /**
             * @description 스토리지 프로바이더 (기본값: OCI). 허용 값: OCI, R2
             * @default OCI
             * @example OCI
             * @enum {string}
             */
            storageProvider: "OCI" | "R2";
        };
        UpdateProjectRequest: {
            /**
             * @description 프로젝트 이름 (1-50자)
             * @example 수정된 프로젝트 이름
             */
            name?: string;
            /**
             * @description 프로젝트 설명 (최대 200자)
             * @example 수정된 프로젝트 설명
             */
            description?: string;
        };
        ProjectResponse: {
            /**
             * @description 프로젝트 ID
             * @example clq1234abcd
             */
            id: string;
            /**
             * @description 프로젝트 이름
             * @example 내 웹사이트 에셋
             */
            name: string;
            /**
             * @description 프로젝트 설명
             * @example 웹사이트에서 사용할 이미지 모음
             */
            description: string | null;
            /**
             * @description 스토리지 프로바이더
             * @example OCI
             * @enum {string}
             */
            storageProvider: "OCI" | "R2";
            /**
             * @description 생성 일시 (ISO 8601)
             * @example 2023-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description 수정 일시 (ISO 8601)
             * @example 2023-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        ProjectDetailsResponse: components["schemas"]["ProjectResponse"] & {
            /** @description 프로젝트에 속한 파일 목록 */
            files: components["schemas"]["FileResponse"][];
        };
        ProjectListResponse: components["schemas"]["ProjectResponse"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
